name: testopenpa
version: '0.1'
summary: This is a test openpa app
description: This is a test openpa app
grade: devel
confinement: strict
base: core18

apps:
  testopenpa:
    command: bin/TestOpenPA
    plugs:
    - network
    - audio-playback
    - pulseaudio

parts:
  xwintest:
    plugin: dotnet
    dotnet-version: 5.0
    dotnet-runtime-version: '5.0.7'
    source: .
    source-type: local
    override-build: |
      dotnet build -c Release
      dotnet publish -r linux-x64 -c Release -p:PublishTrimmed=true --self-contained true -o $SNAPCRAFT_PART_INSTALL/bin/
      chmod 0755 $SNAPCRAFT_PART_INSTALL/bin/TestOpenPA
    stage-packages:
    - libpulse0   
    
environment:
  LD_LIBRARY_PATH: ${LD_LIBRARY_PATH}:${SNAP}/lib/:${SNAP}/lib/${SNAPCRAFT_ARCH_TRIPLET}/:${SNAP}/usr/lib/:${SNAP}/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/
  PATH: $SNAP/bin/:$SNAP/usr/bin/:${PATH}
  PULSE_SERVER: /var/run/pulse/native